[package]
name = "poke_electrum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bitcoin = "0.29.2"
electrum-client = "0.12.0"